// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;

namespace HotelManagment.Domain.Models;

public class ApplicationUser:IdentityUser
{
    public int EmployeeId { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? LastLogin { get; set; }

    public virtual Employee Employee { get; set; }
}